# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
export HOST=`route |grep default|awk '{print $2}'`

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
